### ISSUE TITLE
FLEXing DOES work without Activator…

### ISSUE THREAD

**Issue by NSExceptional** [ShyamLad/Flex12#1]
I made FLEXing work without activator… by long pressing on the status bar (see: BigBoss or the `statusbar-activation` branch of the repo). This is redundant. 

And why did you not just ask me first before making a clone? 🙃

**Comment by ShyamLad** [comment]
I genuinely did not realize that branch. However this is not a clone since we have different approaches. I made this simple implementation for personal use and have no intention of releasing this to a big repo.
