### ISSUE TITLE
Using 3D touch is a kind of a stupid idea

### ISSUE THREAD

**Issue by jakeajames** [ShyamLad/Flex12#2]
**Is your feature request related to a problem? Please describe.**
Only 9 devices from everything Apple has ever released have 3D touch lol, what about the rest of us poor users.

**Describe the solution you'd like**
Long-press

**Describe alternatives you've considered**
nothing

**Additional context**
nothing

**Comment by ShyamLad** [comment]
Yep makes sense to add it. Will add long-press on status bar soon. Thanks for the input!

**Comment by ShyamLad** [comment]
Added Long-Press (2 second). Also works in unsandboxed apps now.
